import JSZip from 'jszip';
import { saveAs } from 'file-saver';

export async function exportCreativeDirection(direction: any, request: string, userVisualDna: string, references: any[]) {
  const zip = new JSZip();

  // Create a README
  zip.file("README.md", `# ${direction.concept || 'Project Concept'}

## Visual Mood
${direction.visualMood}

## Typography
${direction.typographyDirection}

## Color System
${direction.colorDirection}

## Originality Strategy
${direction.originalityStrategy}

*Generated by Pinterest AI Design Intelligence*
`);

  // Call the backend to generate the functional project files
  try {
    const res = await fetch('/api/gemini/generate-project', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ direction, request, userVisualDna, references })
    });
    
    if (!res.ok) {
      throw new Error("Failed to generate project source");
    }

    const { project } = await res.json();
    
    if (project && project.files) {
      let hasPackageJson = false;
      let hasIndexHtml = false;
      let hasMainTsx = false;

      for (const file of project.files) {
        // Ensure path uses forward slashes
        const filePath = file.path.replace(/\\/g, '/');
        zip.file(filePath, file.content);
        
        if (filePath === 'package.json') hasPackageJson = true;
        if (filePath === 'index.html') hasIndexHtml = true;
        if (filePath === 'src/main.tsx') hasMainTsx = true;
      }

      // Add fallbacks for critical files if the AI didn't include them
      if (!hasPackageJson) {
        zip.file("package.json", JSON.stringify({
          name: "generated-concept",
          private: true,
          version: "0.0.0",
          type: "module",
          scripts: {
            dev: "vite",
            build: "tsc && vite build",
            preview: "vite preview"
          },
          dependencies: {
            "react": "^18.2.0",
            "react-dom": "^18.2.0",
            "lucide-react": "^0.263.1"
          },
          devDependencies: {
            "@types/react": "^18.2.15",
            "@types/react-dom": "^18.2.7",
            "@vitejs/plugin-react": "^4.0.3",
            "tailwindcss": "^3.3.0",
            "autoprefixer": "^10.4.14",
            "postcss": "^8.4.24",
            "typescript": "^5.0.2",
            "vite": "^4.4.5"
          }
        }, null, 2));
      }

      if (!hasIndexHtml) {
        zip.file("index.html", `<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>${direction.concept || 'App'}</title>
    <script src="https://cdn.tailwindcss.com"></script>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.tsx"></script>
  </body>
</html>`);
      }

      if (!hasMainTsx) {
        zip.file("src/main.tsx", `import React from 'react'
import ReactDOM from 'react-dom/client'
import App from './App.tsx'

ReactDOM.createRoot(document.getElementById('root')!).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>,
)`);
      }
    } else {
       throw new Error("Invalid output format");
    }
  } catch (err) {
    console.error("Project generation failed:", err);
    alert("Project generation failed. Exporting only creative direction README.");
  }

  const content = await zip.generateAsync({ type: "blob" });
  saveAs(content, "creative-direction-export.zip");
}
